In [243]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
#import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [244]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [245]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)  # Evaluate the model on the test set

c:\Users\arisa\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9740740740740741

In [246]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)  # Evaluate the model on the test set

0.987037037037037

In [247]:
rf = RandomForestClassifier(n_estimators=50)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)  # Evaluate the model on the test set

0.9703703703703703

In [248]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [249]:
for train_index, text_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print("TRAIN:", train_index, "TEST:", text_index)

TRAIN: [3 4 5 6 7 8] TEST: [0 1 2]
TRAIN: [0 1 2 6 7 8] TEST: [3 4 5]
TRAIN: [0 1 2 3 4 5] TEST: [6 7 8]


In [250]:
def get_score(model, x_train,  x_test,y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [251]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)


In [252]:
scores_l =[]
scores_svm =[]
scores_rf =[]





for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]

    scores_l.append(get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [253]:
scores_l

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [254]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [255]:
scores_rf 

[0.9348914858096828, 0.9582637729549248, 0.9181969949916527]

In [256]:
from sklearn.model_selection import cross_val_score


In [257]:
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target, cv=folds)

array([0.91986644, 0.94156928, 0.91652755])

In [258]:
cross_val_score(svm, digits.data, digits.target, cv=folds)

array([0.96494157, 0.97996661, 0.96494157])

In [259]:
cross_val_score(rf, digits.data, digits.target, cv=folds)

array([0.92821369, 0.95659432, 0.91652755])